#!/bin/sh

echo "Application ..."
vendor/bin/lessc assets/less/build.less assets/compiled/main.css

echo "Bootstrap ..."
vendor/bin/lessc vendor/twbs/bootstrap/less/bootstrap.less assets/compiled/bootstrap.css
