#!/bin/sh

echo "1 - Generate environment dependent configuration"
echo "================================================"
vendor/bin/karma hydrate

echo "2 - Compile assets"
echo "=================="
./lessc

echo "3 - Package assets"
echo "=================="
./console assetic:dump
